### ISSUE TITLE
Parsing error on (large? deeply nested?) problem

### ISSUE THREAD

**Issue by lex-lex** [TobiasGleissner/embed_modal#2]
The parser of the tool gives up on problem [GAL016+1.p](https://github.com/TobiasGleissner/embed_modal/files/1542633/GAL016.1.txt) and others, too.

Is there something that can be done? 
Java: 

> openjdk version "1.8.0_151"
> OpenJDK Runtime Environment (build 1.8.0_151-b12)
> OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

Error message:

> Dec 8, 2017 1:25:55 PM transformation.Wrappers lambda$convertModalMultipleSemanticsOnMultipleDirectoriesTraverseDirectory$4 - INFO: Processing 524: /home/lex/TPTP/modal/GAL/GAL016+1.p
> Dec 8, 2017 1:25:55 PM transformation.Wrappers convertModalToString - INFO: Processing /home/lex/TPTP/modal/GAL/GAL016+1.p using additional semantics k_constant_rigid_global
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at parser.ThfAstGen.parse(ThfAstGen.java:47)
> 	at transformation.Wrappers.convertModalToString(Wrappers.java:286)
> 	at transformation.Wrappers.convertModal(Wrappers.java:335)
> 	at transformation.Wrappers.lambda$convertModalMultipleSemanticsOnMultipleDirectoriesTraverseDirectory$4(Wrappers.java:90)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at transformation.Wrappers.convertModalMultipleSemanticsOnMultipleDirectoriesTraverseDirectory(Wrappers.java:76)
> 	at main.EmbedModal.main(EmbedModal.java:247)
> Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
> 	at org.antlr.v4.runtime.misc.DoubleKeyMap.put(DoubleKeyMap.java:25)
> 	at org.antlr.v4.runtime.atn.PredictionContext.mergeSingletons(PredictionContext.java:234)
> 	at org.antlr.v4.runtime.atn.PredictionContext.merge(PredictionContext.java:155)
> 	at org.antlr.v4.runtime.atn.PredictionContext.mergeSingletons(PredictionContext.java:225)
> 	at org.antlr.v4.runtime.atn.PredictionContext.merge(PredictionContext.java:155)
> 	at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:154)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1529)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1583)
> 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
> Dec 8, 2017 1:32:40 PM transformation.Wrappers convertModal - SEVERE: exceptions.ParseException
> Dec 8, 2017 1:32:40 PM transformation.Wrappers lambda$convertModalMultipleSemanticsOnMultipleDirectoriesTraverseDirectory$4 - WARNING: ParseError: Could not convert /home/lex/TPTP/modal/GAL/GAL016+1.p

**Comment by TobiasScholl** [comment]
According to [Stackoverflow](https://stackoverflow.com/questions/1393486/error-java-lang-outofmemoryerror-gc-overhead-limit-exceeded) this happens if the garbage collector uses much more CPU time (per default 98%) than the actual software. 

The Java option

> -XX:-UseGCOverheadLimit

will supress this exception. Execution might be slow doing this. Increasing the heap size could lessen this problem.

Please report if this helps.
