### ISSUE TITLE
mrel is not specified if neither $box nor $dia is used in the problem

### ISSUE THREAD

**Issue by lex-lex** [TobiasGleissner/embed_modal#3]
See SET008+3.p (QMLTP). The problem does not contain $box or $dia so `mrel` is not introduced to the embedded problem. But if translating with varying domain semantics the definition of the quantifier/the exists in world predicates require `mrel`. Hence, the ATP systems report an error.
Always specifiy `mrel` or simplify the definition of quantifiers if no box/dia is used in problem?

**Comment by TobiasScholl** [comment]
Has been resolved some time ago. If no modal operators are introduced the optimized version of the original problem is returned which again is the original problem.
